
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.roguelike
{ 
    public enum EChoicePool
    {
        Reward = 0,
        Rest = 1,
        Treasure = 2,
        Shop = 3,
    }

} 

