
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.roguelike
{ 
    public enum EEffectType
    {
        None = 0,
        AddAttack = 1,
        AddDefense = 2,
        Heal = 3,
        AddMaxHealth = 4,
        AddCritChance = 5,
        AddGold = 6,
        AddPickupRadius = 7,
        AddProjectileDamageMultiplier = 8,
        AddMoveSpeed = 9,
    }

} 

