
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.roguelike
{ 
    public enum EEnemyTier
    {
        Common = 0,
        Elite = 1,
        Boss = 2,
    }

} 

