
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
public sealed partial class Effect : Luban.BeanBase
{
    public Effect(ByteBuf _buf) 
    {
        Type = (roguelike.EEffectType)_buf.ReadInt();
        Value = _buf.ReadFloat();
    }

    public static Effect DeserializeEffect(ByteBuf _buf)
    {
        return new roguelike.Effect(_buf);
    }

    /// <summary>
    /// ????
    /// </summary>
    public readonly roguelike.EEffectType Type;
    /// <summary>
    /// ???
    /// </summary>
    public readonly float Value;
   
    public const int __ID__ = 1212312014;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

