
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
public sealed partial class RoguelikeEnemy : Luban.BeanBase
{
    public RoguelikeEnemy(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        DisplayName = _buf.ReadString();
        Tier = (roguelike.EEnemyTier)_buf.ReadInt();
        MaxHealth = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Defense = _buf.ReadInt();
        CritChance = _buf.ReadFloat();
        CritMultiplier = _buf.ReadFloat();
    }

    public static RoguelikeEnemy DeserializeRoguelikeEnemy(ByteBuf _buf)
    {
        return new roguelike.RoguelikeEnemy(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 显示名称
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 敌人层级
    /// </summary>
    public readonly roguelike.EEnemyTier Tier;
    /// <summary>
    /// 最大生命
    /// </summary>
    public readonly int MaxHealth;
    /// <summary>
    /// 攻击
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 防御
    /// </summary>
    public readonly int Defense;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float CritChance;
    /// <summary>
    /// 暴击倍率
    /// </summary>
    public readonly float CritMultiplier;
   
    public const int __ID__ = 638906580;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "displayName:" + DisplayName + ","
        + "tier:" + Tier + ","
        + "maxHealth:" + MaxHealth + ","
        + "attack:" + Attack + ","
        + "defense:" + Defense + ","
        + "critChance:" + CritChance + ","
        + "critMultiplier:" + CritMultiplier + ","
        + "}";
    }
}
}

