
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
public sealed partial class RoguelikeChoice : Luban.BeanBase
{
    public RoguelikeChoice(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Title = _buf.ReadString();
        Desc = _buf.ReadString();
        PoolType = (roguelike.EChoicePool)_buf.ReadInt();
        Cost = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); Effects = new System.Collections.Generic.List<roguelike.Effect>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { roguelike.Effect _e0;  _e0 = global::GameConfig.roguelike.Effect.DeserializeEffect(_buf); Effects.Add(_e0);}}
    }

    public static RoguelikeChoice DeserializeRoguelikeChoice(ByteBuf _buf)
    {
        return new roguelike.RoguelikeChoice(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// ??
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// ??
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// ????
    /// </summary>
    public readonly roguelike.EChoicePool PoolType;
    /// <summary>
    /// ??
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// ????
    /// </summary>
    public readonly System.Collections.Generic.List<roguelike.Effect> Effects;
   
    public const int __ID__ = -1731238443;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Effects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "title:" + Title + ","
        + "desc:" + Desc + ","
        + "poolType:" + PoolType + ","
        + "cost:" + Cost + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "}";
    }
}
}

