
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
public sealed partial class RoguelikeRelic : Luban.BeanBase
{
    public RoguelikeRelic(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        DisplayName = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Effects = new System.Collections.Generic.List<roguelike.Effect>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { roguelike.Effect _e0;  _e0 = global::GameConfig.roguelike.Effect.DeserializeEffect(_buf); Effects.Add(_e0);}}
    }

    public static RoguelikeRelic DeserializeRoguelikeRelic(ByteBuf _buf)
    {
        return new roguelike.RoguelikeRelic(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 显示名称
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 效果列表
    /// </summary>
    public readonly System.Collections.Generic.List<roguelike.Effect> Effects;
   
    public const int __ID__ = 650650815;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Effects) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "displayName:" + DisplayName + ","
        + "desc:" + Desc + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "}";
    }
}
}

