
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
public sealed partial class RoguelikeSpawnStage : Luban.BeanBase
{
    public RoguelikeSpawnStage(ByteBuf _buf)
    {
        Id = _buf.ReadInt();
        StartTime = _buf.ReadFloat();
        CommonSpawnCount = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); CommonEnemyIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); CommonEnemyIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); CommonWeights = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); CommonWeights.Add(_e0);}}
        EliteEnemyId = _buf.ReadString();
        EliteStartTime = _buf.ReadFloat();
        BossEnemyId = _buf.ReadString();
        BossStartTime = _buf.ReadFloat();
        HealthGrowthPerMinute = _buf.ReadInt();
    }

    public static RoguelikeSpawnStage DeserializeRoguelikeSpawnStage(ByteBuf _buf)
    {
        return new roguelike.RoguelikeSpawnStage(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 开始时间
    /// </summary>
    public readonly float StartTime;
    /// <summary>
    /// 普通刷怪数量
    /// </summary>
    public readonly int CommonSpawnCount;
    /// <summary>
    /// 普通敌人ID列表
    /// </summary>
    public readonly System.Collections.Generic.List<string> CommonEnemyIds;
    /// <summary>
    /// 普通敌人权重
    /// </summary>
    public readonly System.Collections.Generic.List<int> CommonWeights;
    /// <summary>
    /// 精英敌人ID
    /// </summary>
    public readonly string EliteEnemyId;
    /// <summary>
    /// 精英开始时间
    /// </summary>
    public readonly float EliteStartTime;
    /// <summary>
    /// Boss敌人ID
    /// </summary>
    public readonly string BossEnemyId;
    /// <summary>
    /// Boss开始时间
    /// </summary>
    public readonly float BossStartTime;
    /// <summary>
    /// 每分钟生命成长
    /// </summary>
    public readonly int HealthGrowthPerMinute;

    public const int __ID__ = 1666032247;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "startTime:" + StartTime + ","
        + "commonSpawnCount:" + CommonSpawnCount + ","
        + "commonEnemyIds:" + Luban.StringUtil.CollectionToString(CommonEnemyIds) + ","
        + "commonWeights:" + Luban.StringUtil.CollectionToString(CommonWeights) + ","
        + "eliteEnemyId:" + EliteEnemyId + ","
        + "eliteStartTime:" + EliteStartTime + ","
        + "bossEnemyId:" + BossEnemyId + ","
        + "bossStartTime:" + BossStartTime + ","
        + "healthGrowthPerMinute:" + HealthGrowthPerMinute + ","
        + "}";
    }
}
}
