
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
public sealed partial class RoguelikeWeapon : Luban.BeanBase
{
    public RoguelikeWeapon(ByteBuf _buf)
    {
        Id = _buf.ReadString();
        DisplayName = _buf.ReadString();
        WeaponType = _buf.ReadString();
        BaseDamage = _buf.ReadInt();
        DamageGrowth = _buf.ReadInt();
        BaseInterval = _buf.ReadFloat();
        IntervalGrowth = _buf.ReadFloat();
        BaseRange = _buf.ReadFloat();
        ProjectileSpeed = _buf.ReadFloat();
    }

    public static RoguelikeWeapon DeserializeRoguelikeWeapon(ByteBuf _buf)
    {
        return new roguelike.RoguelikeWeapon(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 显示名称
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 武器类型
    /// </summary>
    public readonly string WeaponType;
    /// <summary>
    /// 基础伤害
    /// </summary>
    public readonly int BaseDamage;
    /// <summary>
    /// 每级伤害成长
    /// </summary>
    public readonly int DamageGrowth;
    /// <summary>
    /// 基础间隔
    /// </summary>
    public readonly float BaseInterval;
    /// <summary>
    /// 每级间隔缩短
    /// </summary>
    public readonly float IntervalGrowth;
    /// <summary>
    /// 基础射程
    /// </summary>
    public readonly float BaseRange;
    /// <summary>
    /// 投射物速度
    /// </summary>
    public readonly float ProjectileSpeed;

    public const int __ID__ = -1161835952;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "displayName:" + DisplayName + ","
        + "weaponType:" + WeaponType + ","
        + "baseDamage:" + BaseDamage + ","
        + "damageGrowth:" + DamageGrowth + ","
        + "baseInterval:" + BaseInterval + ","
        + "intervalGrowth:" + IntervalGrowth + ","
        + "baseRange:" + BaseRange + ","
        + "projectileSpeed:" + ProjectileSpeed + ","
        + "}";
    }
}
}
