
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
/// <summary>
/// 肉鸽武器配置
/// </summary>
public partial class TbRoguelikeWeapon
{
    private readonly System.Collections.Generic.Dictionary<string, roguelike.RoguelikeWeapon> _dataMap;
    private readonly System.Collections.Generic.List<roguelike.RoguelikeWeapon> _dataList;

    public TbRoguelikeWeapon(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, roguelike.RoguelikeWeapon>(n);
        _dataList = new System.Collections.Generic.List<roguelike.RoguelikeWeapon>(n);
        for(int i = n ; i > 0 ; --i)
        {
            roguelike.RoguelikeWeapon _v;
            _v = global::GameConfig.roguelike.RoguelikeWeapon.DeserializeRoguelikeWeapon(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, roguelike.RoguelikeWeapon> DataMap => _dataMap;
    public System.Collections.Generic.List<roguelike.RoguelikeWeapon> DataList => _dataList;

    public roguelike.RoguelikeWeapon GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public roguelike.RoguelikeWeapon Get(string key) => _dataMap[key];
    public roguelike.RoguelikeWeapon this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
