
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
/// <summary>
/// 肉鸽敌人配置
/// </summary>
public partial class TbRoguelikeEnemy
{
    private readonly System.Collections.Generic.Dictionary<string, roguelike.RoguelikeEnemy> _dataMap;
    private readonly System.Collections.Generic.List<roguelike.RoguelikeEnemy> _dataList;
    
    public TbRoguelikeEnemy(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, roguelike.RoguelikeEnemy>(n);
        _dataList = new System.Collections.Generic.List<roguelike.RoguelikeEnemy>(n);
        for(int i = n ; i > 0 ; --i)
        {
            roguelike.RoguelikeEnemy _v;
            _v = global::GameConfig.roguelike.RoguelikeEnemy.DeserializeRoguelikeEnemy(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, roguelike.RoguelikeEnemy> DataMap => _dataMap;
    public System.Collections.Generic.List<roguelike.RoguelikeEnemy> DataList => _dataList;

    public roguelike.RoguelikeEnemy GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public roguelike.RoguelikeEnemy Get(string key) => _dataMap[key];
    public roguelike.RoguelikeEnemy this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

