
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
/// <summary>
/// 肉鸽刷怪阶段配置
/// </summary>
public partial class TbRoguelikeSpawnStage
{
    private readonly System.Collections.Generic.Dictionary<int, roguelike.RoguelikeSpawnStage> _dataMap;
    private readonly System.Collections.Generic.List<roguelike.RoguelikeSpawnStage> _dataList;

    public TbRoguelikeSpawnStage(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, roguelike.RoguelikeSpawnStage>(n);
        _dataList = new System.Collections.Generic.List<roguelike.RoguelikeSpawnStage>(n);
        for(int i = n ; i > 0 ; --i)
        {
            roguelike.RoguelikeSpawnStage _v;
            _v = global::GameConfig.roguelike.RoguelikeSpawnStage.DeserializeRoguelikeSpawnStage(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, roguelike.RoguelikeSpawnStage> DataMap => _dataMap;
    public System.Collections.Generic.List<roguelike.RoguelikeSpawnStage> DataList => _dataList;

    public roguelike.RoguelikeSpawnStage GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public roguelike.RoguelikeSpawnStage Get(int key) => _dataMap[key];
    public roguelike.RoguelikeSpawnStage this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
