
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
public partial class TbRoguelikeChoice
{
    private readonly System.Collections.Generic.Dictionary<string, roguelike.RoguelikeChoice> _dataMap;
    private readonly System.Collections.Generic.List<roguelike.RoguelikeChoice> _dataList;
    
    public TbRoguelikeChoice(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, roguelike.RoguelikeChoice>(n);
        _dataList = new System.Collections.Generic.List<roguelike.RoguelikeChoice>(n);
        for(int i = n ; i > 0 ; --i)
        {
            roguelike.RoguelikeChoice _v;
            _v = global::GameConfig.roguelike.RoguelikeChoice.DeserializeRoguelikeChoice(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, roguelike.RoguelikeChoice> DataMap => _dataMap;
    public System.Collections.Generic.List<roguelike.RoguelikeChoice> DataList => _dataList;

    public roguelike.RoguelikeChoice GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public roguelike.RoguelikeChoice Get(string key) => _dataMap[key];
    public roguelike.RoguelikeChoice this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

