
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.roguelike
{
/// <summary>
/// 肉鸽被动遗物配置
/// </summary>
public partial class TbRoguelikeRelic
{
    private readonly System.Collections.Generic.Dictionary<string, roguelike.RoguelikeRelic> _dataMap;
    private readonly System.Collections.Generic.List<roguelike.RoguelikeRelic> _dataList;
    
    public TbRoguelikeRelic(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, roguelike.RoguelikeRelic>(n);
        _dataList = new System.Collections.Generic.List<roguelike.RoguelikeRelic>(n);
        for(int i = n ; i > 0 ; --i)
        {
            roguelike.RoguelikeRelic _v;
            _v = global::GameConfig.roguelike.RoguelikeRelic.DeserializeRoguelikeRelic(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, roguelike.RoguelikeRelic> DataMap => _dataMap;
    public System.Collections.Generic.List<roguelike.RoguelikeRelic> DataList => _dataList;

    public roguelike.RoguelikeRelic GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public roguelike.RoguelikeRelic Get(string key) => _dataMap[key];
    public roguelike.RoguelikeRelic this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

