
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public roguelike.TbRoguelikeEnemy TbRoguelikeEnemy {get; }
    public roguelike.TbRoguelikeRelic TbRoguelikeRelic {get; }
    public roguelike.TbRoguelikeChoice TbRoguelikeChoice {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbRoguelikeEnemy = new roguelike.TbRoguelikeEnemy(loader("roguelike_tbroguelikeenemy"));
        TbRoguelikeRelic = new roguelike.TbRoguelikeRelic(loader("roguelike_tbroguelikerelic"));
        TbRoguelikeChoice = new roguelike.TbRoguelikeChoice(loader("roguelike_tbroguelikechoice"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbRoguelikeEnemy.ResolveRef(this);
        TbRoguelikeRelic.ResolveRef(this);
        TbRoguelikeChoice.ResolveRef(this);
    }
}

}
